/**
 * Local Pokémon data cache reader.
 *
 * Backing data lives in `pokemon-cache.json` and is generated by
 * `scripts/generate-pokemon-cache.ts` (which calls PokéAPI).
 *
 * At runtime the app should consult this module FIRST and only fall back to
 * any other resolution (local sprite id map, hardcoded type fallbacks) if the
 * lookup returns undefined. No PokéAPI network calls happen on normal render.
 *
 * To refresh the cache:
 *   npx tsx scripts/generate-pokemon-cache.ts
 *   # commit the resulting pokemon-cache.json
 */

import cacheJson from './pokemon-cache.json';
import type { PokemonType } from '@/app/nuzlocke/types';

export type CachedPokemon = {
  /** National-dex ID (e.g. 122 for Mr. Mime). */
  id: number;
  /** PokéAPI canonical lowercase slug, e.g. "nidoran-f". */
  name: string;
  /** Same as `name`, kept for readability at call sites. */
  slug: string;
  /** Capitalized type names as used elsewhere in the app, e.g. ["Poison"]. */
  types: PokemonType[];
  /** Stable sprite URL on the PokéAPI GitHub sprite mirror. */
  spriteUrl: string;
  /** Generation introduced, 1..9. */
  generation: number;
  /** Optional flat evolution chain of canonical PokéAPI slugs. */
  evolution?: string[];
  /** Schema v2+: non-hidden abilities, in PokéAPI slot order, capitalized. */
  abilities?: string[];
  /** Schema v2+: hidden ability slot(s), if any, capitalized. */
  hiddenAbilities?: string[];
};

type CacheFile = {
  generatedAt: string | null;
  source: string;
  schemaVersion: number;
  pokemon: CachedPokemon[];
};

const cache = cacheJson as CacheFile;
const pokemonList: CachedPokemon[] = Array.isArray(cache?.pokemon) ? cache.pokemon : [];

/**
 * Aggressively normalizes a display name or slug to a single canonical lookup
 * key. Handles every edge case the codebase has historically run into:
 *   "Mr. Mime"   -> "mr-mime"
 *   "MrMime"     -> "mrmime"  (alias added separately)
 *   "Farfetch'd" -> "farfetchd"
 *   "Nidoran♀"   -> "nidoran-f"
 *   "Nidoran♂"   -> "nidoran-m"
 *   "NidoranF"   -> "nidoranf" (alias added separately)
 */
function normalizeKey(species: string): string {
  if (!species) return '';
  return species
    .toLowerCase()
    .replace(/♀/g, '-f')
    .replace(/♂/g, '-m')
    .replace(/['’.]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/** Extra aliases for display-name forms the slugifier alone won't match. */
const displayAliases: Record<string, string> = {
  MrMime: 'mr-mime',
  'Mr. Mime': 'mr-mime',
  'Mr. Rime': 'mr-rime',
  MrRime: 'mr-rime',
  "Farfetch'd": 'farfetchd',
  "Sirfetch'd": 'sirfetchd',
  'Nidoran♀': 'nidoran-f',
  'Nidoran♂': 'nidoran-m',
  NidoranF: 'nidoran-f',
  NidoranM: 'nidoran-m',
  Flabébé: 'flabebe',
  HoOh: 'ho-oh',
  'Ho-oh': 'ho-oh',
  Porygon2: 'porygon2',
  PorygonZ: 'porygon-z',
  'Porygon-Z': 'porygon-z',
};

const lookup = new Map<string, CachedPokemon>();

for (const entry of pokemonList) {
  if (!entry || !entry.slug) continue;
  const slugKey = normalizeKey(entry.slug);
  if (slugKey) lookup.set(slugKey, entry);
  const nameKey = normalizeKey(entry.name);
  if (nameKey) lookup.set(nameKey, entry);
}

for (const [display, slug] of Object.entries(displayAliases)) {
  const cached = lookup.get(normalizeKey(slug));
  if (cached) {
    lookup.set(normalizeKey(display), cached);
    lookup.set(display.toLowerCase(), cached);
  }
}

/**
 * Look up cached species data by any of: display name, PokéAPI slug,
 * gender-symbol form, or condensed form like "NidoranF".
 * Returns undefined when the cache hasn't been populated yet OR the species
 * isn't present — callers must handle undefined safely.
 */
export function getCachedPokemon(species: string): CachedPokemon | undefined {
  if (!species) return undefined;
  // Try as-passed (display alias map covers oddballs even when slug differs).
  const direct = lookup.get(normalizeKey(species));
  if (direct) return direct;
  // Try first segment of slash-joined forms ("Tauros / Tauros-Paldea" -> "Tauros").
  const head = species.split('/')[0]?.trim();
  if (head && head !== species) {
    const headHit = lookup.get(normalizeKey(head));
    if (headHit) return headHit;
  }
  return undefined;
}

export function getCachedPokemonTypes(species: string): PokemonType[] | undefined {
  const entry = getCachedPokemon(species);
  if (!entry || !Array.isArray(entry.types) || entry.types.length === 0) return undefined;
  return entry.types;
}

export function getCachedPokemonSpriteUrl(species: string): string | undefined {
  const entry = getCachedPokemon(species);
  return entry?.spriteUrl || undefined;
}

export function getCachedPokemonId(species: string): number | undefined {
  return getCachedPokemon(species)?.id;
}

/**
 * Returns the union of non-hidden + hidden abilities (non-hidden first, in slot
 * order). Always returns an array — empty if the species isn't cached, the
 * cache hasn't been regenerated with schema v2+, or the entry has no abilities.
 * Callers do not need to re-normalize the species name.
 */
export function getCachedPokemonAbilities(species: string): string[] {
  const entry = getCachedPokemon(species);
  if (!entry) return [];
  const normal = Array.isArray(entry.abilities) ? entry.abilities : [];
  const hidden = Array.isArray(entry.hiddenAbilities) ? entry.hiddenAbilities : [];
  // Dedupe (rare, but a hidden slot can occasionally repeat a normal name).
  const seen = new Set<string>();
  const out: string[] = [];
  for (const value of [...normal, ...hidden]) {
    if (!value || seen.has(value)) continue;
    seen.add(value);
    out.push(value);
  }
  return out;
}

export function getCachedPokemonGeneration(species: string): number | undefined {
  return getCachedPokemon(species)?.generation;
}

export function isPokemonCachePopulated(): boolean {
  return pokemonList.length > 0;
}

/**
 * Returns a flat list of canonical display names from the cache, sorted by national-dex ID.
 * Useful for populating searchable comboboxes / `<datalist>` suggestion sets without forcing
 * callers to import the JSON directly.
 */
let cachedDisplayNameList: string[] | null = null;
export function getAllCachedPokemonNames(): string[] {
  if (cachedDisplayNameList) return cachedDisplayNameList;
  const names = pokemonList
    .slice()
    .sort((a, b) => (a.id ?? 0) - (b.id ?? 0))
    .map((p) => {
      // Convert PokéAPI slug ("mr-mime") to a display-ish name ("Mr-mime") — callers typically
      // resolve against the canonical alias table when re-keying, but for autocomplete the slug
      // form is fine.
      const slug = p.slug || p.name;
      if (!slug) return '';
      // Special-case the most common name reversals so the dropdown is readable.
      if (slug === 'mr-mime') return 'Mr. Mime';
      if (slug === 'mr-rime') return 'Mr. Rime';
      if (slug === 'farfetchd') return "Farfetch'd";
      if (slug === 'sirfetchd') return "Sirfetch'd";
      if (slug === 'nidoran-f') return 'NidoranF';
      if (slug === 'nidoran-m') return 'NidoranM';
      if (slug === 'flabebe') return 'Flabébé';
      // Generic Title-Case fallback for everything else.
      return slug
        .split('-')
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join(' ');
    })
    .filter((name): name is string => Boolean(name));
  cachedDisplayNameList = names;
  return names;
}

export function getPokemonCacheGeneratedAt(): string | null {
  return cache?.generatedAt ?? null;
}
