import type { GameVersion, NuzlockeBoss, PokemonType, RunType } from './types';

export const nuzlockeStorageKey = 'repeatchannel_nuzlocke_runs';

export const gameGroups: { generation: string; games: { name: GameVersion; supported: boolean }[] }[] = [
  { generation: 'Gen 1', games: ['Red', 'Blue', 'Yellow'].map((name) => ({ name: name as GameVersion, supported: false })) },
  { generation: 'Gen 2', games: ['Gold', 'Silver', 'Crystal'].map((name) => ({ name: name as GameVersion, supported: false })) },
  { generation: 'Gen 3', games: ['Ruby', 'Sapphire', 'Emerald', 'FireRed', 'LeafGreen'].map((name) => ({ name: name as GameVersion, supported: false })) },
  { generation: 'Gen 4', games: ['Diamond', 'Pearl', 'Platinum', 'HeartGold', 'SoulSilver'].map((name) => ({ name: name as GameVersion, supported: false })) },
  { generation: 'Gen 5', games: ['Black', 'White', 'Black 2', 'White 2'].map((name) => ({ name: name as GameVersion, supported: false })) },
  { generation: 'Gen 6', games: ['X', 'Y', 'Omega Ruby', 'Alpha Sapphire'].map((name) => ({ name: name as GameVersion, supported: false })) },
  { generation: 'Gen 7', games: ['Sun', 'Moon', 'Ultra Sun', 'Ultra Moon'].map((name) => ({ name: name as GameVersion, supported: false })) },
  {
    generation: 'Gen 8',
    games: ['Sword', 'Shield', 'Brilliant Diamond', 'Shining Pearl', 'Legends: Arceus'].map((name) => ({
      name: name as GameVersion,
      supported: false,
    })),
  },
  { generation: 'Gen 9', games: ['Scarlet', 'Violet'].map((name) => ({ name: name as GameVersion, supported: true })) },
];

export const runTypes: RunType[] = [
  'Standard Nuzlocke',
  'Hardcore Nuzlocke',
  'Monotype',
  'Randomizer',
  'Soul Link',
  'Egglocke',
  'Custom Rules',
];

export const pokemonTypes: PokemonType[] = [
  'Normal',
  'Fire',
  'Water',
  'Grass',
  'Electric',
  'Ice',
  'Fighting',
  'Poison',
  'Ground',
  'Flying',
  'Psychic',
  'Bug',
  'Rock',
  'Ghost',
  'Dragon',
  'Dark',
  'Steel',
  'Fairy',
];

export const scarletVioletLocations = [
  'Starter',
  'Cabo Poco',
  'Poco Path',
  'South Province Area One',
  'South Province Area Two',
  'South Province Area Three',
  'South Province Area Four',
  'South Province Area Five',
  'South Province Area Six',
  'West Province Area One',
  'West Province Area Two',
  'West Province Area Three',
  'East Province Area One',
  'East Province Area Two',
  'East Province Area Three',
  'North Province Area One',
  'North Province Area Two',
  'North Province Area Three',
  'Asado Desert',
  'Tagtree Thicket',
  'Glaseado Mountain',
  'Casseroya Lake',
  'Socarrat Trail',
  'The Great Crater of Paldea',
  'Area Zero',
  'Tera Raid',
  'Gift / Static',
];

export type EncounterOption = {
  species: string;
  types: PokemonType[];
  abilities?: string[];
  surfMethod?: boolean;
  fishingMethod?: boolean;
};

export const natureOptions = [
  'Not Sure',
  'Hardy (neutral)',
  'Lonely (+Atk / -Def)',
  'Brave (+Atk / -Spe)',
  'Adamant (+Atk / -SpA)',
  'Naughty (+Atk / -SpD)',
  'Bold (+Def / -Atk)',
  'Docile (neutral)',
  'Relaxed (+Def / -Spe)',
  'Impish (+Def / -SpA)',
  'Lax (+Def / -SpD)',
  'Timid (+Spe / -Atk)',
  'Hasty (+Spe / -Def)',
  'Serious (neutral)',
  'Jolly (+Spe / -SpA)',
  'Naive (+Spe / -SpD)',
  'Modest (+SpA / -Atk)',
  'Mild (+SpA / -Def)',
  'Quiet (+SpA / -Spe)',
  'Bashful (neutral)',
  'Rash (+SpA / -SpD)',
  'Calm (+SpD / -Atk)',
  'Gentle (+SpD / -Def)',
  'Sassy (+SpD / -Spe)',
  'Careful (+SpD / -SpA)',
  'Quirky (neutral)',
];

export const heldItemOptions = [
  'None',
  'Not Sure',
  'Berry',
  'Oran Berry',
  'Sitrus Berry',
  'Leftovers',
  'Shell Bell',
  'Eviolite',
  'Focus Sash',
  'Choice Band',
  'Choice Specs',
  'Choice Scarf',
  'Life Orb',
  'Rocky Helmet',
  'Assault Vest',
  'Expert Belt',
  'Muscle Band',
  'Wise Glasses',
  'Black Sludge',
  'Booster Energy',
  'Clear Amulet',
  'Loaded Dice',
  'Covert Cloak',
  'Mirror Herb',
  'Punching Glove',
  'Ability Shield',
  'Type-boosting Item',
  'Other',
];

export const commonAbilityOptions = [
  'Not Sure',
  'Primary Ability',
  'Secondary Ability',
  'Hidden Ability',
];

export const speciesAbilityOptions: Record<string, string[]> = {
  Sprigatito: ['Overgrow', 'Protean', 'Not Sure'],
  Fuecoco: ['Blaze', 'Unaware', 'Not Sure'],
  Quaxly: ['Torrent', 'Moxie', 'Not Sure'],
  Lechonk: ['Aroma Veil', 'Gluttony', 'Thick Fat', 'Not Sure'],
  Tarountula: ['Insomnia', 'Stakeout', 'Not Sure'],
  Fletchling: ['Big Pecks', 'Gale Wings', 'Not Sure'],
  Hoppip: ['Chlorophyll', 'Leaf Guard', 'Infiltrator', 'Not Sure'],
  Pawmi: ['Static', 'Natural Cure', 'Iron Fist', 'Not Sure'],
  Scatterbug: ['Shield Dust', 'Compound Eyes', 'Friend Guard', 'Not Sure'],
  Yungoos: ['Stakeout', 'Strong Jaw', 'Adaptability', 'Not Sure'],
  Fidough: ['Own Tempo', 'Klutz', 'Not Sure'],
  Smoliv: ['Early Bird', 'Harvest', 'Not Sure'],
  Mareep: ['Static', 'Plus', 'Not Sure'],
  Maschiff: ['Intimidate', 'Run Away', 'Stakeout', 'Not Sure'],
  Shinx: ['Rivalry', 'Intimidate', 'Guts', 'Not Sure'],
  Ralts: ['Synchronize', 'Trace', 'Telepathy', 'Not Sure'],
  Nacli: ['Purifying Salt', 'Sturdy', 'Clear Body', 'Not Sure'],
  Charcadet: ['Flash Fire', 'Flame Body', 'Not Sure'],
  Tinkatink: ['Mold Breaker', 'Own Tempo', 'Pickpocket', 'Not Sure'],
  Cyclizar: ['Shed Skin', 'Regenerator', 'Not Sure'],
  Frigibax: ['Thermal Exchange', 'Ice Body', 'Not Sure'],
  Gimmighoul: ['Rattled', 'Not Sure'],
};

export function getAbilityOptions(species: string) {
  return speciesAbilityOptions[species] ?? commonAbilityOptions;
}

export const pokemonSpriteIds: Record<string, number> = {
  Sprigatito: 906,
  Fuecoco: 909,
  Quaxly: 912,
  Lechonk: 915,
  Tarountula: 917,
  Fletchling: 661,
  Hoppip: 187,
  Pawmi: 921,
  Scatterbug: 664,
  Yungoos: 734,
  Fidough: 926,
  Smoliv: 928,
  Igglybuff: 174,
  Combee: 415,
  Mareep: 179,
  Maschiff: 942,
  Shinx: 403,
  Drowzee: 96,
  Nacli: 932,
  Rookidee: 821,
  Charcadet: 935,
  Tadbulb: 938,
  Makuhita: 296,
  Shroodle: 944,
  Squawkabilly: 931,
  Pikachu: 25,
  Applin: 840,
  Deerling: 585,
  Pineco: 204,
  Mudbray: 749,
  Teddiursa: 216,
  Flittle: 955,
  Pawmo: 922,
  Goomy: 704,
  Croagunk: 453,
  Toxel: 848,
  Capsakid: 951,
  Tinkatink: 957,
  Gible: 443,
  Larvitar: 246,
  Bagon: 371,
  Meditite: 307,
  Salandit: 757,
  Noibat: 714,
  Axew: 610,
  Nymble: 919,
  Wattrel: 940,
  Finizen: 963,
  Bombirdier: 962,
  Girafarig: 203,
  Tauros: 128,
  Silicobra: 843,
  Rufflet: 627,
  Toedscool: 948,
  Foongus: 590,
  Dunsparce: 206,
  Komala: 775,
  Zorua: 570,
  Mimikyu: 778,
  Shuppet: 353,
  Pincurchin: 871,
  Eelektrik: 603,
  Cyclizar: 967,
  Varoom: 965,
  Oricorio: 741,
  Murkrow: 198,
  Mareanie: 747,
  Bramblin: 946,
  Orthworm: 968,
  Sandile: 551,
  Cacnea: 331,
  Rolycoly: 837,
  Numel: 322,
  Spoink: 325,
  Glimmet: 969,
  Klefki: 707,
  Cufant: 878,
  Torkoal: 324,
  Bronzor: 436,
  Sableye: 302,
  Tinkatuff: 958,
  Bisharp: 625,
  Sneasel: 215,
  Hawlucha: 701,
  Falinks: 870,
  Noivern: 715,
  Lurantis: 754,
  Heracross: 214,
  Scyther: 123,
  Forretress: 205,
  Venomoth: 49,
  Tropius: 357,
  Ursaring: 217,
  Cetoddle: 974,
  Snom: 872,
  Eiscue: 875,
  Bergmite: 712,
  Cubchoo: 613,
  Frigibax: 996,
  Rellor: 953,
  Hippopotas: 449,
  Grafaiai: 945,
  Impidimp: 859,
  Morgrem: 860,
  Toedscruel: 949,
  Cryogonal: 615,
  Snorunt: 361,
  Greavard: 971,
  Dondozo: 977,
  Tatsugiri: 978,
  Veluza: 976,
  Dratini: 147,
  Gyarados: 130,
  Slowpoke: 79,
  Persian: 53,
  Glimmora: 970,
  Dugtrio: 51,
  Corviknight: 823,
  Raichu: 26,
  Medicham: 308,
  Espathra: 956,
  Farigiraf: 981,
  'Great Tusk': 984,
  'Iron Treads': 990,
  'Scream Tail': 985,
  'Iron Bundle': 991,
  'Roaring Moon': 1005,
  'Iron Valiant': 1006,
  Wooper: 194,
  Petilil: 548,
  Bellibolt: 939,
  Luxio: 404,
  Wugtrio: 961,
  Crabominable: 740,
  Dudunsparce: 982,
  Staraptor: 398,
  Banette: 354,
  Houndstone: 972,
  Toxtricity: 849,
  Gardevoir: 282,
  Florges: 671,
  Frosmoth: 873,
  Beartic: 614,
  Cetitan: 975,
  Altaria: 334,
  Klawf: 950,
  Pawniard: 624,
  Skuntank: 435,
  Muk: 89,
  Revavroom: 966,
  Azumarill: 184,
  Wigglytuff: 40,
  Dachsbun: 927,
  Toxicroak: 454,
  Passimian: 766,
  Lucario: 448,
  Annihilape: 979,
  Lycanroc: 745,
  Pawmot: 923,
  Goodra: 706,
  Gogoat: 673,
  Avalugg: 713,
  Kingambit: 983,
};

export function getPokemonSpriteUrl(species: string) {
  const cleanSpecies = species.split('/')[0]?.trim();
  const id = cleanSpecies ? pokemonSpriteIds[cleanSpecies] : undefined;
  return id ? `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${id}.png` : '';
}

const starterOptions: EncounterOption[] = [
  { species: 'Sprigatito', types: ['Grass'] },
  { species: 'Fuecoco', types: ['Fire'] },
  { species: 'Quaxly', types: ['Water'] },
];

export const scarletVioletEncounterOptions: Record<string, EncounterOption[]> = {
  Starter: starterOptions,
  'Cabo Poco': [
    { species: 'Lechonk', types: ['Normal'] },
    { species: 'Tarountula', types: ['Bug'] },
    { species: 'Fletchling', types: ['Normal', 'Flying'] },
    { species: 'Hoppip', types: ['Grass', 'Flying'] },
  ],
  'Poco Path': [
    { species: 'Lechonk', types: ['Normal'] },
    { species: 'Tarountula', types: ['Bug'] },
    { species: 'Pawmi', types: ['Electric'] },
    { species: 'Hoppip', types: ['Grass', 'Flying'] },
    { species: 'Scatterbug', types: ['Bug'] },
    { species: 'Fletchling', types: ['Normal', 'Flying'] },
    { species: 'Yungoos', types: ['Normal'] },
  ],
  'South Province Area One': [
    { species: 'Lechonk', types: ['Normal'] },
    { species: 'Tarountula', types: ['Bug'] },
    { species: 'Pawmi', types: ['Electric'] },
    { species: 'Fletchling', types: ['Normal', 'Flying'] },
    { species: 'Hoppip', types: ['Grass', 'Flying'] },
    { species: 'Scatterbug', types: ['Bug'] },
    { species: 'Azurill', types: ['Normal', 'Fairy'], surfMethod: true },
    { species: 'Buizel', types: ['Water'], surfMethod: true },
    { species: 'Wooper', types: ['Poison', 'Ground'] },
    { species: 'Ralts', types: ['Psychic', 'Fairy'] },
    { species: 'Psyduck', types: ['Water'], surfMethod: true },
  ],
  'South Province Area Two': [
    { species: 'Fidough', types: ['Fairy'] },
    { species: 'Smoliv', types: ['Grass', 'Normal'] },
    { species: 'Igglybuff', types: ['Normal', 'Fairy'] },
    { species: 'Combee', types: ['Bug', 'Flying'] },
    { species: 'Mareep', types: ['Electric'] },
    { species: 'Maschiff', types: ['Dark'] },
    { species: 'Shinx', types: ['Electric'] },
    { species: 'Drowzee', types: ['Psychic'] },
  ],
  'South Province Area Three': [
    { species: 'Nacli', types: ['Rock'] },
    { species: 'Rookidee', types: ['Flying'] },
    { species: 'Charcadet', types: ['Fire'] },
    { species: 'Tadbulb', types: ['Electric'] },
    { species: 'Makuhita', types: ['Fighting'] },
    { species: 'Shroodle', types: ['Poison', 'Normal'] },
    { species: 'Squawkabilly', types: ['Normal', 'Flying'] },
  ],
  'South Province Area Four': [
    { species: 'Pikachu', types: ['Electric'] },
    { species: 'Applin', types: ['Grass', 'Dragon'] },
    { species: 'Deerling', types: ['Normal', 'Grass'] },
    { species: 'Pineco', types: ['Bug'] },
    { species: 'Mudbray', types: ['Ground'] },
    { species: 'Teddiursa', types: ['Normal'] },
    { species: 'Combee', types: ['Bug', 'Flying'] },
  ],
  'South Province Area Five': [
    { species: 'Flittle', types: ['Psychic'] },
    { species: 'Pawmo', types: ['Electric', 'Fighting'] },
    { species: 'Goomy', types: ['Dragon'] },
    { species: 'Croagunk', types: ['Poison', 'Fighting'] },
    { species: 'Toxel', types: ['Electric', 'Poison'] },
    { species: 'Capsakid', types: ['Grass'] },
    { species: 'Tinkatink', types: ['Fairy', 'Steel'] },
  ],
  'South Province Area Six': [
    { species: 'Gible', types: ['Dragon', 'Ground'] },
    { species: 'Larvitar', types: ['Rock', 'Ground'] },
    { species: 'Bagon', types: ['Dragon'] },
    { species: 'Meditite', types: ['Fighting', 'Psychic'] },
    { species: 'Salandit', types: ['Poison', 'Fire'] },
    { species: 'Noibat', types: ['Flying', 'Dragon'] },
    { species: 'Axew', types: ['Dragon'] },
  ],
  'West Province Area One': [
    { species: 'Nymble', types: ['Bug'] },
    { species: 'Wattrel', types: ['Electric', 'Flying'] },
    { species: 'Finizen', types: ['Water'], surfMethod: true },
    { species: 'Maschiff', types: ['Dark'] },
    { species: 'Bombirdier', types: ['Flying', 'Dark'] },
    { species: 'Tadbulb', types: ['Electric'] },
    { species: 'Shroodle', types: ['Poison', 'Normal'] },
  ],
  'West Province Area Two': [
    { species: 'Girafarig', types: ['Normal', 'Psychic'] },
    { species: 'Tauros', types: ['Fighting'] },
    { species: 'Capsakid', types: ['Grass'] },
    { species: 'Silicobra', types: ['Ground'] },
    { species: 'Rufflet', types: ['Normal', 'Flying'] },
    { species: 'Toedscool', types: ['Ground', 'Grass'] },
    { species: 'Foongus', types: ['Grass', 'Poison'] },
  ],
  'West Province Area Three': [
    { species: 'Dunsparce', types: ['Normal'] },
    { species: 'Komala', types: ['Normal'] },
    { species: 'Zorua', types: ['Dark'] },
    { species: 'Mimikyu', types: ['Ghost', 'Fairy'] },
    { species: 'Shuppet', types: ['Ghost'] },
    { species: 'Pincurchin', types: ['Electric'] },
    { species: 'Eelektrik', types: ['Electric'] },
  ],
  'East Province Area One': [
    { species: 'Cyclizar', types: ['Dragon', 'Normal'] },
    { species: 'Wattrel', types: ['Electric', 'Flying'] },
    { species: 'Varoom', types: ['Steel', 'Poison'] },
    { species: 'Oricorio', types: ['Fire', 'Flying'] },
    { species: 'Murkrow', types: ['Dark', 'Flying'] },
    { species: 'Mareanie', types: ['Poison', 'Water'], fishingMethod: true },
    { species: 'Toxel', types: ['Electric', 'Poison'] },
  ],
  'East Province Area Two': [
    { species: 'Bramblin', types: ['Grass', 'Ghost'] },
    { species: 'Orthworm', types: ['Steel'] },
    { species: 'Sandile', types: ['Ground', 'Dark'] },
    { species: 'Cacnea', types: ['Grass'] },
    { species: 'Rolycoly', types: ['Rock'] },
    { species: 'Numel', types: ['Fire', 'Ground'] },
    { species: 'Spoink', types: ['Psychic'] },
  ],
  'East Province Area Three': [
    { species: 'Varoom', types: ['Steel', 'Poison'] },
    { species: 'Glimmet', types: ['Rock', 'Poison'] },
    { species: 'Klefki', types: ['Steel', 'Fairy'] },
    { species: 'Cufant', types: ['Steel'] },
    { species: 'Torkoal', types: ['Fire'] },
    { species: 'Bronzor', types: ['Steel', 'Psychic'] },
    { species: 'Sableye', types: ['Dark', 'Ghost'] },
  ],
  'North Province Area One': [
    { species: 'Tinkatuff', types: ['Fairy', 'Steel'] },
    { species: 'Bisharp', types: ['Dark', 'Steel'] },
    { species: 'Sneasel', types: ['Dark', 'Ice'] },
    { species: 'Hawlucha', types: ['Fighting', 'Flying'] },
    { species: 'Falinks', types: ['Fighting'] },
    { species: 'Noivern', types: ['Flying', 'Dragon'] },
    { species: 'Lurantis', types: ['Grass'] },
  ],
  'North Province Area Two': [
    { species: 'Bisharp', types: ['Dark', 'Steel'] },
    { species: 'Heracross', types: ['Bug', 'Fighting'] },
    { species: 'Scyther', types: ['Bug', 'Flying'] },
    { species: 'Forretress', types: ['Bug', 'Steel'] },
    { species: 'Venomoth', types: ['Bug', 'Poison'] },
    { species: 'Tropius', types: ['Grass', 'Flying'] },
    { species: 'Ursaring', types: ['Normal'] },
  ],
  'North Province Area Three': [
    { species: 'Cetoddle', types: ['Ice'] },
    { species: 'Snom', types: ['Ice', 'Bug'] },
    { species: 'Sneasel', types: ['Dark', 'Ice'] },
    { species: 'Eiscue', types: ['Ice'] },
    { species: 'Bergmite', types: ['Ice'] },
    { species: 'Cubchoo', types: ['Ice'] },
    { species: 'Frigibax', types: ['Dragon', 'Ice'] },
  ],
  'Asado Desert': [
    { species: 'Sandile', types: ['Ground', 'Dark'] },
    { species: 'Silicobra', types: ['Ground'] },
    { species: 'Rellor', types: ['Bug'] },
    { species: 'Cacnea', types: ['Grass'] },
    { species: 'Hippopotas', types: ['Ground'] },
    { species: 'Bramblin', types: ['Grass', 'Ghost'] },
    { species: 'Capsakid', types: ['Grass'] },
  ],
  'Tagtree Thicket': [
    { species: 'Shroodle', types: ['Poison', 'Normal'] },
    { species: 'Grafaiai', types: ['Poison', 'Normal'] },
    { species: 'Impidimp', types: ['Dark', 'Fairy'] },
    { species: 'Morgrem', types: ['Dark', 'Fairy'] },
    { species: 'Foongus', types: ['Grass', 'Poison'] },
    { species: 'Toedscool', types: ['Ground', 'Grass'] },
    { species: 'Zorua', types: ['Dark'] },
  ],
  'Glaseado Mountain': [
    { species: 'Cetoddle', types: ['Ice'] },
    { species: 'Snom', types: ['Ice', 'Bug'] },
    { species: 'Bergmite', types: ['Ice'] },
    { species: 'Cryogonal', types: ['Ice'] },
    { species: 'Snorunt', types: ['Ice'] },
    { species: 'Frigibax', types: ['Dragon', 'Ice'] },
    { species: 'Greavard', types: ['Ghost'] },
  ],
  'Casseroya Lake': [
    { species: 'Dondozo', types: ['Water'], surfMethod: true },
    { species: 'Tatsugiri', types: ['Dragon', 'Water'], surfMethod: true },
    { species: 'Veluza', types: ['Water', 'Psychic'], surfMethod: true },
    { species: 'Dratini', types: ['Dragon'], fishingMethod: true },
    { species: 'Gyarados', types: ['Water', 'Flying'], fishingMethod: true },
    { species: 'Slowpoke', types: ['Water', 'Psychic'], surfMethod: true },
    { species: 'Mareanie', types: ['Poison', 'Water'], fishingMethod: true },
  ],
  'Socarrat Trail': [
    { species: 'Zorua', types: ['Dark'] },
    { species: 'Mimikyu', types: ['Ghost', 'Fairy'] },
    { species: 'Komala', types: ['Normal'] },
    { species: 'Persian', types: ['Normal'] },
    { species: 'Dunsparce', types: ['Normal'] },
    { species: 'Toedscruel', types: ['Ground', 'Grass'] },
    { species: 'Grafaiai', types: ['Poison', 'Normal'] },
  ],
  'The Great Crater of Paldea': [
    { species: 'Glimmet', types: ['Rock', 'Poison'] },
    { species: 'Glimmora', types: ['Rock', 'Poison'] },
    { species: 'Dugtrio', types: ['Ground'] },
    { species: 'Corviknight', types: ['Flying', 'Steel'] },
    { species: 'Raichu', types: ['Electric'] },
    { species: 'Medicham', types: ['Fighting', 'Psychic'] },
    { species: 'Espathra', types: ['Psychic'] },
  ],
  'Area Zero': [
    { species: 'Glimmora', types: ['Rock', 'Poison'] },
    { species: 'Dudunsparce', types: ['Normal'] },
    { species: 'Farigiraf', types: ['Normal', 'Psychic'] },
    { species: 'Great Tusk', types: ['Ground', 'Fighting'] },
    { species: 'Iron Treads', types: ['Ground', 'Steel'] },
    { species: 'Scream Tail', types: ['Fairy', 'Psychic'] },
    { species: 'Iron Bundle', types: ['Ice', 'Water'], surfMethod: true },
    { species: 'Roaring Moon', types: ['Dragon', 'Dark'] },
    { species: 'Iron Valiant', types: ['Fairy', 'Fighting'] },
  ],
  'Tera Raid': [
    { species: 'Tera Raid Encounter', types: ['Normal'] },
    { species: 'Raid Den Choice', types: ['Normal'] },
  ],
  'Gift / Static': [
    { species: 'Mystery Gift / Static', types: ['Normal'] },
    { species: 'Gimmighoul', types: ['Ghost'] },
    { species: 'Charcadet', types: ['Fire'] },
    { species: 'Wooper', types: ['Poison', 'Ground'] },
  ],
};

const bossPokemon = (species: string, level: number, ability = 'Not listed', item = 'None listed', nature = 'Not listed') => ({
  species,
  level,
  ability,
  item,
  nature,
});

export const scarletVioletBosses: NuzlockeBoss[] = [
  { id: 'katy', name: 'Katy', category: 'Victory Road Gym', levelCap: 15, completed: false, notes: '', deaths: 0, pokemon: [bossPokemon('Nymble', 14), bossPokemon('Tarountula', 14), bossPokemon('Teddiursa', 15)] },
  { id: 'brassius', name: 'Brassius', category: 'Victory Road Gym', levelCap: 17, completed: false, notes: '', deaths: 0, pokemon: [bossPokemon('Petilil', 16), bossPokemon('Smoliv', 16), bossPokemon('Sudowoodo', 17)] },
  { id: 'iono', name: 'Iono', category: 'Victory Road Gym', levelCap: 24, completed: false, notes: '', deaths: 0, pokemon: [bossPokemon('Wattrel', 23), bossPokemon('Bellibolt', 23), bossPokemon('Luxio', 23), bossPokemon('Mismagius', 24, 'Levitate')] },
  { id: 'kofu', name: 'Kofu', category: 'Victory Road Gym', levelCap: 30, completed: false, notes: '', deaths: 0, pokemon: [bossPokemon('Veluza', 29), bossPokemon('Wugtrio', 29), bossPokemon('Crabominable', 30)] },
  { id: 'larry', name: 'Larry', category: 'Victory Road Gym', levelCap: 36, completed: false, notes: '', deaths: 0, pokemon: [bossPokemon('Komala', 35), bossPokemon('Dudunsparce', 35), bossPokemon('Staraptor', 36)] },
  { id: 'ryme', name: 'Ryme', category: 'Victory Road Gym', levelCap: 42, completed: false, notes: '', deaths: 0, pokemon: [bossPokemon('Mimikyu', 41), bossPokemon('Banette', 41), bossPokemon('Houndstone', 41), bossPokemon('Toxtricity', 42)] },
  { id: 'tulip', name: 'Tulip', category: 'Victory Road Gym', levelCap: 45, completed: false, notes: '', deaths: 0, pokemon: [bossPokemon('Farigiraf', 44), bossPokemon('Gardevoir', 44), bossPokemon('Espathra', 44), bossPokemon('Florges', 45)] },
  { id: 'grusha', name: 'Grusha', category: 'Victory Road Gym', levelCap: 48, completed: false, notes: '', deaths: 0, pokemon: [bossPokemon('Frosmoth', 47), bossPokemon('Beartic', 47), bossPokemon('Cetitan', 47), bossPokemon('Altaria', 48)] },
  { id: 'klawf', name: 'Stony Cliff Titan', category: 'Path of Legends Titan', levelCap: 16, completed: false, notes: '', deaths: 0, pokemon: [bossPokemon('Klawf', 16)] },
  { id: 'bombirdier', name: 'Open Sky Titan', category: 'Path of Legends Titan', levelCap: 20, completed: false, notes: '', deaths: 0, pokemon: [bossPokemon('Bombirdier', 20)] },
  { id: 'orthworm', name: 'Lurking Steel Titan', category: 'Path of Legends Titan', levelCap: 29, completed: false, notes: '', deaths: 0, pokemon: [bossPokemon('Orthworm', 29)] },
  { id: 'great-tusk-iron-treads', name: 'Quaking Earth Titan', category: 'Path of Legends Titan', levelCap: 45, completed: false, notes: '', deaths: 0, pokemon: [bossPokemon('Great Tusk / Iron Treads', 45)] },
  { id: 'tatsugiri', name: 'False Dragon Titan', category: 'Path of Legends Titan', levelCap: 57, completed: false, notes: '', deaths: 0, pokemon: [bossPokemon('Dondozo', 56), bossPokemon('Tatsugiri', 57)] },
  { id: 'giacomo', name: 'Giacomo', category: 'Starfall Street Base', levelCap: 21, completed: false, notes: '', deaths: 0, pokemon: [bossPokemon('Pawniard', 21), bossPokemon('Segin Starmobile', 20)] },
  { id: 'mela', name: 'Mela', category: 'Starfall Street Base', levelCap: 27, completed: false, notes: '', deaths: 0, pokemon: [bossPokemon('Torkoal', 27), bossPokemon('Schedar Starmobile', 26)] },
  { id: 'atticus', name: 'Atticus', category: 'Starfall Street Base', levelCap: 33, completed: false, notes: '', deaths: 0, pokemon: [bossPokemon('Skuntank', 32), bossPokemon('Muk', 32), bossPokemon('Revavroom', 33), bossPokemon('Navi Starmobile', 32)] },
  { id: 'ortega', name: 'Ortega', category: 'Starfall Street Base', levelCap: 51, completed: false, notes: '', deaths: 0, pokemon: [bossPokemon('Azumarill', 50), bossPokemon('Wigglytuff', 50), bossPokemon('Dachsbun', 51), bossPokemon('Ruchbah Starmobile', 50)] },
  { id: 'eri', name: 'Eri', category: 'Starfall Street Base', levelCap: 56, completed: false, notes: '', deaths: 0, pokemon: [bossPokemon('Toxicroak', 55), bossPokemon('Passimian', 55), bossPokemon('Lucario', 55), bossPokemon('Annihilape', 56), bossPokemon('Caph Starmobile', 56)] },
  { id: 'rival-nemona', name: 'Nemona Rival Fights', category: 'Rival', levelCap: 66, completed: false, notes: '', deaths: 0, pokemon: [bossPokemon('Lycanroc', 65), bossPokemon('Pawmot', 65), bossPokemon('Goodra', 65), bossPokemon('Dudunsparce', 65), bossPokemon('Orthworm', 65), bossPokemon('Starter Ace', 66)] },
  { id: 'elite-four', name: 'Elite Four', category: 'Pokemon League', levelCap: 61, completed: false, notes: '', deaths: 0, pokemon: [bossPokemon('Rika Team', 58), bossPokemon('Poppy Team', 59), bossPokemon('Larry Team', 60), bossPokemon('Hassel Team', 61)] },
  { id: 'champion-geeta', name: 'Champion Geeta', category: 'Pokemon League', levelCap: 62, completed: false, notes: '', deaths: 0, pokemon: [bossPokemon('Espathra', 61), bossPokemon('Gogoat', 61), bossPokemon('Veluza', 61), bossPokemon('Avalugg', 61), bossPokemon('Kingambit', 61), bossPokemon('Glimmora', 62)] },
  { id: 'final-stories', name: 'Final Story Fights', category: 'Finale', levelCap: 67, completed: false, notes: '', deaths: 0, pokemon: [bossPokemon('Arven Team', 63), bossPokemon('AI Professor Team', 67), bossPokemon('Final Legendary Fight', 68)] },
];

export const typeColors: Record<PokemonType, string> = {
  Normal: 'bg-[#d9d3c3] text-[#2f2a22]',
  Fire: 'bg-[#ff8a4c] text-[#2b1308]',
  Water: 'bg-[#6db8ff] text-[#061a31]',
  Grass: 'bg-[#79d66b] text-[#08260a]',
  Electric: 'bg-[#ffe36e] text-[#282000]',
  Ice: 'bg-[#9be7ff] text-[#09242d]',
  Fighting: 'bg-[#d15a4d] text-white',
  Poison: 'bg-[#b76ee0] text-white',
  Ground: 'bg-[#d9b36a] text-[#271a04]',
  Flying: 'bg-[#a7c5ff] text-[#121d38]',
  Psychic: 'bg-[#ff76b5] text-[#341022]',
  Bug: 'bg-[#b8d94f] text-[#1f2702]',
  Rock: 'bg-[#b8a06a] text-[#211806]',
  Ghost: 'bg-[#7964bd] text-white',
  Dragon: 'bg-[#7158ff] text-white',
  Dark: 'bg-[#66574d] text-white',
  Steel: 'bg-[#c3c8d2] text-[#20252d]',
  Fairy: 'bg-[#ffaad6] text-[#321223]',
};
